# This file should contain all the record creation needed to seed the database with its default values.
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

# 10.times do
#   Player.create(username: Faker::Internet.unique.username(5..10))
# end

Game.create(player_id: 1, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 1, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 1, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 1, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 2, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 2, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 2, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 2, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 3, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 3, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 4, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 4, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 4, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 4, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 5, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 5, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 5, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 5, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 5, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 6, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 7, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 7, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 7, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 8, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 8, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 8, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 8, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 9, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 9, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 9, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 9, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 9, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 9, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 9, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
Game.create(player_id: 10, computer_move: rand(1..3), player_move: rand(1..3), game_score: rand(0..1))
